//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationInfo
    {
        public int reservedBy { get; set; }
        public int reservationNumber { get; set; }
        public Nullable<System.DateTime> reservationDate { get; set; }
        public Nullable<int> durationTime { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
    }
}
