//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int roomNumber { get; set; }
        public string roomLocation { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> roomFloor { get; set; }
        public string roomStatus { get; set; }
    }
}
