//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemAdmin
    {
        public int ID { get; set; }
        public string contact { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
    }
}
